untitled/config/routes.rb
Rails.application.routes.draw do
  resources :event_wrappers
  resources :websites
  resources :events
  resources :results

  get 'websites/:id/show_siblings' => 'website#get_ancestors_node', as: :show_siblings

end

untitled/app/models/website.rb
class Website < ActiveRecord::Base
  serialize :results, Hash
  serialize :data, Array
  has_one :result
  has_one :event_wrapper
  has_many :events

  after_create :create_result_and_event_wrapper

  def types
    ["Event side","Event kalender med undersider","Event kalender med alt info"]
  end

  def create_result_and_event_wrapper
    self.result = Result.new(:website_id => self.id, :data => [])
    self.event_wrapper = EventWrapper.new(:website_id => self.id)
  end

end

untitled/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  include ScraperHelper
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)
    @website.results =  start_search(@website.url)
    @html = get_html(@website.url)
    @atts = get_all_elements(@website.url)
    # @atts = removeAllNoneTagNodes(@atts)
    respond_to do |format|
      if @website.save
        @result = @website.result
        if @website.page_type == @website.types.first
          format.html { redirect_to edit_result_path(@website.result), :result => @result}
        else
          format.html { render "websites/find-event-wrapper", :result => @result}
          format.json { render :show, status: :created, location: @website }
        end
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:name, :url, :page_type)
    end
end

untitled/app/helpers/websites_helper.rb
module WebsitesHelper

  def save_data
    p "PARAMS DATA!!!!! #{params[:data]}"
    @website.data = params[:data]
    @website.save
  end

end

untitled/app/views/websites/_form.html.erb
<%= form_for(@website) do |f| %>
  <% if @website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% @website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
    <div class="field">
      <%= "Side type" %><br>
      <%= select_tag 'website[page_type]', options_for_select(@website.types)%>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

untitled/app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form' %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

untitled/app/views/websites/find-event-wrapper.erb
<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<strong>Attribute:</strong>
<% @atts.each do |p| %>
    <% f = p.text.gsub("\n", "").gsub("\r","").gsub(" ", "") %>
    <% if f.length > 0 %>
    <div>
      <%= link_to 'select' , edit_event_wrapper_path(@website.event_wrapper, :element => p.path)%>
      <%= ": #{p.text}" %>
    </div>
    <% end %>
<%end%>

</br>
<%= link_to 'back', website_path(@website) %>

untitled/app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Websites</h1>

<%= link_to 'New Website', new_website_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Page Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= website.url %></td>
        <td><%= website.page_type%></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

untitled/app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form' %>

<%= link_to 'Back', websites_path %>

untitled/app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>