untitled/config/routes.rb
Rails.application.routes.draw do
  resources :event_wrappers
  resources :websites
  resources :events
  resources :results

  get 'websites/:id/show_siblings' => 'website#get_ancestors_node', as: :show_siblings

end

untitled/app/models/result.rb
class Result < ActiveRecord::Base
  serialize :data, Array
  serialize :hashed_data, Array
  belongs_to :website

end

untitled/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  include DateHelper, ScraperHelper, ListEventHelper
  helper_method :get_array_with_hashs_from_to_arrays_of_same_size
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /Results
  # GET /Results.json
  def index
    @results = Result.all
  end

  # GET /Results/1
  # GET /Results/1.json
  def show
  end

  # GET /Results/new
  def new
    @result = Result.new
  end

  # GET /Results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /Results
  # POST /Results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Results/1
  # PATCH/PUT /Results/1.json
  def update

    respond_to do |format|
      if @result.update(result_params )
        if @result.hashed_data.size < @result.data.size
          format.html {redirect_to edit_result_path(@result)}
        else
          if @result.website.page_type == @result.website.types[1]
            scrapeEvents(@result.website.id)
            format.html { redirect_to websites_path}
          else
            create_event(format)
          end
          # if @event != nil
          #   format.html { redirect_to event_path(@event), notice: 'Event was created' }
          # else
          #   format.html { redirect_to @result, notice: 'Result was successfully updated.' }
          #   format.json { render :show, status: :ok, location: @result }
          # end
        end
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Results/1
  # DELETE /Results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_array_with_hashs_from_to_arrays_of_same_size(a1, a2)
    array = Array.new
    if a1.size == a2.size
      i = 0
      while i < a1.size
        hash = Hash[a1[i] => a2[i]]
        array[array.size] = hash
        i = i +1
      end
    end
    return array
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.permit(:time_format,{:hashed_data => []},{:data => []})
    end

    def create_event(format)
      if @result.link_url == nil
      url = @result.website.url
      else
        url = @result.link_url
        end
      title = ""
      date = ""
      venue_name = ""
      price = ""
      description = ""
      keys = @result.hashed_data
      values = @result.data
      array_with_hashes = get_array_with_hashs_from_to_arrays_of_same_size(keys, values)
      array_with_hashes.each do |d|
        d = d.to_a
        case
          when d[0][0] == "titel"
            title = title + get_node_from_xpath(url,d[0][1]).text
          when d[0][0] == "tidspunkt"
            date = date + get_node_from_xpath(url,d[0][1]).text
          when d[0][0] == "beskrivelse"
            description = "#{description}#{get_node_from_xpath(url,d[0][1]).text} "
          when d[0][0] == "pris"
            price = price + get_node_from_xpath(url,d[0][1]).text
          when d[0][0] == "sted"
            venue_name = venue_name + get_node_from_xpath(url,d[0][1]).text
        end
      end
      date = get_date_from_string(date,@result.time_format)
      price = get_numbers(price).first
      @event = Event.new(:title => title, :website_id => @result.website_id.to_i , :happens_at => date, :venue_name => venue_name, :price => price, :description => description)
      if @event.save
        format.html { redirect_to event_path(@event), notice: 'Event was created' }
      end
    end
end

untitled/app/helpers/results_helper.rb
module ResultsHelper
end

untitled/app/views/Results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <% if @result.data.blank? %>
    <div class="field">
      <% if @result.link_url == nil %>
      <% atts = get_all_elements(@result.website.url)%>
          <% atts.each do |p| %>
              <% q = p.text.gsub("\n", "").gsub("\r","").gsub(" ", "") %>
              <% if q.to_s.length > 0 %>
              <div>
                <%= check_box_tag "data[]", get_xpath_from_node(p)%>
                <%= p.text %>
              </div>
                  <% end %>
          <%end%>
          <% else %>
          <% atts = get_all_elements(@result.link_url)%>
          <% atts.each do |p| %>
              <% q = p.text.gsub("\n", "").gsub("\r","").gsub(" ", "") %>
              <% if q.to_s.length > 0 %>
                  <div>
                    <%= check_box_tag "data[]", get_xpath_from_node(p)%>
                    <%= p.text %>
                  </div>
              <% end %>
          <%end%>
      <% end%>
    </div>
        <% end %>

    <% if !@result.data.blank? %>
        <div class="field">
          <%= "Specificer dato format " %>
          <%=select_tag "time_format", options_for_select(date_formats.map{|s| s}) %>
        </div>

        <div class="field">
          <% @result.data.each do |d| %>
              <% if @result.link_url == nil %>
              <% text = get_node_from_xpath(@result.website.url, d).text %>
                <% else %>
              <% text = get_node_from_xpath(@result.link_url, d).text %>
                  <% end %>
              <% q = text.gsub("\n", "").gsub("\r","").gsub(" ", "") %>
              <% if q.length > 0 %>
              <p>
            <%= select_tag "hashed_data[]", options_for_select(['','titel','tidspunkt', 'beskrivelse','pris','sted'].map{|s| [s, s]}) %>
            <%= text %>
              </p>
                  <% end %>
          <% end %>
        </div>
    <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

untitled/app/views/Results/edit.html.erb
<h1>
  Valgt data for
  <%= @result.website.name %>
</h1>

<h3>
  Url:
  <% if @result.link_url == nil %>
      <%= @result.website.url %>
      <% else %>
  <%= @result.link_url %>
  <% end %>
</h3>
<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

untitled/app/views/Results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

untitled/app/views/Results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

untitled/app/views/Results/show-website-result.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<strong>Attribute:</strong>
<% @atts.each do |p| %>
    <div>
      <%= check_box_tag 'data[]', get_xpath_from_node(p)%>
      <%= p.text %>
    </div>
<%end%>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %> |
<%= link_to 'Continue', edit_result_path(@website.result) %>

untitled/app/views/Results/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  Results for:
  <%= @result.website.name %>
</h1>
<h3>
  Url:
  <%= @result.website.url %>
</h3>

<% array_with_hashes = get_array_with_hashs_from_to_arrays_of_same_size(@result.hashed_data, @result.data) %>
<p>

</p>
<% array_with_hashes.each do |h| %>
    <div>
      <% h = h.to_a %>
      <%= "#{h[0][0]} :" %>
      <%= get_node_from_xpath(@result.website.url, h[0][1]).text %>
    </div>
<% end %>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>