untitled/config/routes.rb
Rails.application.routes.draw do
  resources :event_wrappers
  resources :websites
  resources :events
  resources :results

  get 'websites/:id/show_siblings' => 'website#get_ancestors_node', as: :show_siblings

end

untitled/app/models/event_wrapper.rb
class EventWrapper < ActiveRecord::Base
  belongs_to :website


end

untitled/app/controllers/event_wrappers_controller.rb
require 'uri'

class EventWrappersController < ApplicationController
  before_action :set_event_wrapper, only: [:show, :edit, :update, :destroy]
  include ScraperHelper, UrlHelper

  # GET /event_wrappers
  # GET /event_wrappers.json
  def index
    @event_wrappers = EventWrapper.all
  end

  # GET /event_wrappers/1
  # GET /event_wrappers/1.json
  def show
  end

  # GET /event_wrappers/new
  def new
    @event_wrapper = EventWrapper.new
  end

  # GET /event_wrappers/1/edit
  def edit
  end

  # POST /event_wrappers
  # POST /event_wrappers.json
  def create
    @event_wrapper = EventWrapper.new(event_wrapper_params)

    respond_to do |format|
      if @event_wrapper.save
        format.html { redirect_to @event_wrapper, notice: 'Event wrapper was successfully created.' }
        format.json { render :show, status: :created, location: @event_wrapper }
      else
        format.html { render :new }
        format.json { render json: @event_wrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_wrappers/1
  # PATCH/PUT /event_wrappers/1.json
  def update
    params[:identifier] = @event_wrapper.identifier
    if params[:href_css] != nil
      params[:href_css] = params[:href_css]
    end
    respond_to do |format|
      if @event_wrapper.update(event_wrapper_params)
        if @event_wrapper.href_css != nil
        @result = @event_wrapper.website.result
        nodes = get_all_nodes_with_css_class(get_html(@event_wrapper.website.url),@event_wrapper.identifier)
        links = get_all_nodes_with_css_class(nodes.first,@event_wrapper.href_css).first.attribute("href").text
        if !is_url(links)
          uri = URI.parse(@result.website.url)
          links = uri.scheme + "://" + uri.host + links
          else
          links = links
        end
          @result.update_attributes(:link_url => links)
          format.html {redirect_to edit_result_path(@result)}
        else
        format.html { redirect_to @event_wrapper, notice: "Event wrapper was successfully updated." }
        format.json { render :show, status: :ok, location: @event_wrapper }
        end
      else
        format.html { render :edit }
        format.json { render json: @event_wrapper.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /event_wrappers/1
  # DELETE /event_wrappers/1.json
  def destroy
    @event_wrapper.destroy
    respond_to do |format|
      format.html { redirect_to event_wrappers_url, notice: 'Event wrapper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_wrapper
      @event_wrapper = EventWrapper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_wrapper_params
      params.permit(:identifier, :website_id, :href_css)
    end
end

untitled/app/helpers/event_wrappers_helper.rb
module EventWrappersHelper
  attr_accessor :website_id

  def reload_for_links
    render edit_event_wrapper_path(@event_wrapper)
  end
end

untitled/app/views/event_wrappers/_form.html.erb
<%= form_for(@event_wrapper) do |f| %>
    <% url = @event_wrapper.website.url %>
    <% if @event_wrapper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_wrapper.errors.count, "error") %> prohibited this event_wrapper from being saved:</h2>

      <ul>
      <% @event_wrapper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% url = @event_wrapper.website.url %>
    <% if params[:element] != nil %>
        <% @oldPath = params[:element] %>
        <% @path = remove_last_part_of_path(params[:element]) %>
    <% elsif params[:old_element] != nil %>
        <% @path = params[:old_element] %>
    <% else %>
        <% if @event_wrapper.identifier != nil %>
            <% nodes = get_all_nodes_with_css_class(get_html(@event_wrapper.website.url), @event_wrapper.identifier) %>
            <% @path = nodes.first.path %>
        <% end %>
    <% end %>

    <% if @path != nil %>
        <% nodes = get_node_from_xpath(url, @path) %>
        <% nodes.children.each do |n| %>
            <p>
              <%= n.text %>
            </p>
        <% end %>
        <% if @event_wrapper.website.page_type == @event_wrapper.website.types[1]%>
            <% links = get_all_links(nodes) %>
            <% links.each do |n| %>
                <p>
                  <% if n.attribute("class") != nil %>
                  <%= check_box_tag "href_css", n.attribute('class') %>
                  <%= n.attribute('href') %>
                      <% end %>
                </p>
            <% end %>
        <% end %>
        <% if nodes.attribute('class').class != NilClass %>
            <% @event_wrapper.identifier = nodes.attribute('class').value%>
            <%= "nodes att: #{@event_wrapper.identifier}" %>
            <% @event_wrapper.update(:identifier => nodes.attribute('class').value) %>
        <% end %>
    <% end %>

    <%= f.submit %>
  </div>
<% end %>

untitled/app/views/event_wrappers/edit.html.erb
<h1>Editing Event Wrapper</h1>

<%= render 'form' %>

<br>
<%= link_to 'Step ind', edit_event_wrapper_path(@event_wrapper, :old_path => @oldPath) %> |
<%= link_to 'Step ud', edit_event_wrapper_path(@event_wrapper, :element => @path) %> |
<%= link_to 'Back', event_wrappers_path %>

untitled/app/views/event_wrappers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Event Wrappers</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_wrappers.each do |event_wrapper| %>
      <tr>
        <td><%= event_wrapper.identifier %></td>
        <td><%= link_to 'Show', event_wrapper %></td>
        <td><%= link_to 'Edit', edit_event_wrapper_path(event_wrapper) %></td>
        <td><%= link_to 'Destroy', event_wrapper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event wrapper', new_event_wrapper_path %>

untitled/app/views/event_wrappers/new.html.erb
<h1>New Event Wrapper</h1>

<%= render 'form' %>

<%= link_to 'Back', event_wrappers_path %>

untitled/app/views/event_wrappers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @event_wrapper.identifier %>
</p>

<%= link_to 'Edit', edit_event_wrapper_path(@event_wrapper) %> |
<%= link_to 'Back', event_wrappers_path %>